name = "BlockDFT"
uuid = "4174833f-8ad2-4dcf-87c4-e1a7d5f5dca4"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be>"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
BlockArrays = "0.16"
FFTW = "1.3"
FillArrays = "0.12, 0.13"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
