name = "FourierSubmatrices"
uuid = "b08f63b7-ed5f-487b-9da1-3a3bffd61bbb"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be>"]
version = "0.2.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"

[compat]
BlockArrays = "1.1.1"
FFTW = "1.3"
GenericFFT = "0.1.6"
GenericLinearAlgebra = "0.3.5"
ToeplitzMatrices = "0.8.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
